### ISSUE TITLE
Fix food json aquisition on stallnomanbot.py

### ISSUE THREAD

**Issue by helioloureiro** [helioloureiro/homemadescripts#9]
Create a persistent file which is updated case it is too old (more than one day?).  But do that in a separated thread and, in case of failure - which quite common due busy server - keep the old file instead.

**Comment by thiagoarrais** [comment]
Anyone working on this yet?

**Comment by thiagoarrais** [comment]
How do I run the bot?

Here's what I did:

1. Created a bot with the @BotFather. Obtained an API key.
2. Cloned repo.
3. Created venv:
```
    $ virtualenv venv
    $ . venv/bin/activate
```
4. Installed requirements:
    `pip install -r requirements_stallmanbot.txt`
5. Placed the API key obtained at (1) in `stallmanbot.py` (line 84)
6. Tried running:
    `./stallmanbot.py`
7. Got "no module named 'bs4'"
8. Tried installing bs4
    `pip install bs4`
9. Tried running once more
10. Same error

What am I doing wrong?

I'm using Python 2.7.6

**Comment by helioloureiro** [comment]
> Anyone working on this yet?

Not so far.  You can take it :)

**Comment by helioloureiro** [comment]
> How do I run the bot?
> 
> Here's what I did:
> 
> 1. Created a bot with the @Botfather. Obtained an API key.
> 2. Cloned repo.
> 3. Created venv:
> 
> ```
>     $ virtualenv venv
>     $ . venv/bin/activate
> ```
> 1. Installed requirements:
>    `pip install -r requirements_stallmanbot.txt`
> 2. Placed the API key obtained at (1) in `stallmanbot.py` (line 84)
> 3. Tried running:
>    `./stallmanbot.py`
> 4. Got "no module named 'bs4'"
> 5. Tried installing bs4
>    `pip install bs4`
> 6. Tried running once more
> 7. Same error
> 
> What am I doing wrong?
> 
> I'm using Python 2.7.6

You probably need to run using pip3 since it has been moved from python2.7 toward 3.

Try: pip3 install bs4

**Comment by thiagoarrais** [comment]
Will try it on a Python 3 environment and get back to you.

Em qui, 11 de out de 2018 05:21, Helio Loureiro <notifications@github.com>
escreveu:

**Comment by helioloureiro** [comment]
Fixed on https://github.com/helioloureiro/homemadescripts/commit/5f1c12858b36a231b8b334b540e136e982ae90a5
